ecommfood/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ("web.urls", namespace="web")),
    path('manager/', include ("manager.urls", namespace="manager")),

]

if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

manager/urls.py
from django.urls import path
from manager import views

app_name = "manager"


urlpatterns = [
    path("", views.index, name="index"),
    path("unauthorized_access/", views.unauthorized_access, name="unauthorized_access"),
    
    path('categories/', views.category_list, name='category_list'),
    path('categories/add/', views.add_category, name='add_category'),
    path('categories/edit/<int:id>/', views.edit_category, name='edit_category'),
    path('categories/delete/<int:id>/', views.delete_category, name='delete_category'),
    
    path('products/', views.product_list, name='product_list'),
    path('products/add/', views.add_product, name='add_product'),
    path('products/edit/<int:id>/', views.edit_product, name='edit_product'),
    path('products/delete/<int:id>/', views.delete_product, name='delete_product'),

    path('orders/', views.orders_list, name='orders_list'),

    path("order/Track/<int:id>/", views.order_track, name="order_track"),
    path("order/Cancel/<int:id>/", views.cancel_order, name="cancel_order"),

]

web/urls.py
from django.urls import path
from . import views

app_name = "web"


urlpatterns = [
    path('', views.index, name='index'),
    path('product-list/', views.product_list, name='product_list'),
    path('product/<int:id>/', views.product_detail, name='product_detail'),
    path('add-to-cart/<int:id>/', views.add_cart, name='add_to_cart'),
    path('cart/', views.cart_page, name='cart_page'),
    path('cart/update/<int:id>/', views.update_cart_quantity, name='update_cart_quantity'),
    path('cart/remove/<int:id>/', views.remove_cart_item, name='remove_cart_item'),
    path('checkout/', views.checkout, name='checkout'),
    path('place-order/', views.place_order, name='place_order'),
    path('all-orders/', views.all_orders, name='all_orders'),
    path('order-confirmation/<int:id>/', views.order_confirmation, name='order_confirmation'),
    path('track-order/<int:order_id>/', views.track_order, name='track_order'),
]

manager/models.py
from django.db import models

# Create your models here.

product/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=255)  # The name of the category (e.g., "Spices", "Beverages").
    description = models.TextField(null=True, blank=True)  # A short description about the category.
    image = models.ImageField(upload_to='category_images/', null=True, blank=True)  # Optional image for the category.
    slug = models.SlugField(unique=True)  # A unique slug to be used in the URL for the category.
    created_at = models.DateTimeField(auto_now_add=True)  # Timestamp when the category was created.

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()  # A detailed description of the product.
    price = models.DecimalField(max_digits=10, decimal_places=2)  # Price of the product.
    image = models.ImageField(upload_to='products/', null=True, blank=True)  # Main image for the product.
    image_2 = models.ImageField(upload_to='products/', null=True, blank=True)  # Second image for the product.
    image_3 = models.ImageField(upload_to='products/', null=True, blank=True)  # Third image for the product.
    image_4 = models.ImageField(upload_to='products/', null=True, blank=True)  # Fourth image for the product.
    category = models.ForeignKey(Category, related_name='products', on_delete=models.SET_NULL, null=True)  # Related category.
    stock = models.IntegerField(default=0)  # The quantity of the product in stock.
    weight = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)  # Optional weight of the product (for shipping calculations).
    is_active = models.BooleanField(default=True)  # Whether the product is currently available for purchase.
    created_at = models.DateTimeField(auto_now_add=True)  # Timestamp when the product was added.
    updated_at = models.DateTimeField(auto_now=True)  # Timestamp when the product was last updated.

    def __str__(self):
        return self.name

manager/forms.py
from django import forms
from web.models import *
from custemer.models import *


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description', 'image', 'slug']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter category name'
            }),
            'description': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'placeholder': 'Enter a brief description of the category (optional)'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
            'slug': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter a unique slug for the category'
            }),
        }
        labels = {
            'name': 'Category Name',
            'description': 'Description',
            'image': 'Category Image',
            'slug': 'Slug (Unique URL Identifier)',
        }

    def clean_slug(self):
        slug = self.cleaned_data.get('slug')
        if Category.objects.filter(slug=slug).exists():
            raise forms.ValidationError('The slug must be unique. This one already exists.')
        return slug




class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'name', 
            'description', 
            'price', 
            'image', 
            'image_2', 
            'image_3', 
            'image_4', 
            'category', 
            'stock', 
            'weight', 
            'is_active'
        ]

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Product Name'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Product Description'}),
            'price': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Price'}),
            'stock': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Stock Quantity'}),
            'weight': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Weight (optional)'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'image_2': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'image_3': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'image_4': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

manager/views.py
from main.decorators import allow_manager

from main.functions import generate_form_errors


# Create your views here.
from django.shortcuts import render, get_object_or_404, redirect, reverse

from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

from django.contrib.auth.decorators import login_required
from users.models import User
from custemer.models import *


from web.models import *


from django.contrib.auth import logout as auth_logout

from django.contrib import messages
from .forms import *
 # Ensure only logged-in users can access the index view


@login_required(login_url='manager:login')
@allow_manager
def index(request):
    
    return render(request, 'manager/index.html')



def unauthorized_access(request):
    
    return render(request, 'manager/unauthorized_access.html')



# store_category_list

def category_list(request):
    instances = Category.objects.all()

    context = {
            "instances": instances,
            
    }
    return render(request, 'manager/category_list.html', context=context)




def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category added successfully!')
            return redirect('manager:category_list')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = CategoryForm()

    return render(request, 'manager/category_form.html', {'form': form})


def delete_category(request, id):
    category = get_object_or_404(Category, id=id)
    if request.method == 'POST':
        category.delete()
        messages.success(request, 'Category deleted successfully!')
        return redirect('web:category_list')

    return render(request, 'category_confirm_delete.html', {'category': category})



def edit_category(request, id):
    category = get_object_or_404(Category, id=id)
    if request.method == 'POST':
        form = CategoryForm(request.POST, request.FILES, instance=category)
        if form.is_valid():
            form.save()
            messages.success(request, 'Category updated successfully!')
            return redirect('web:category_list')
        else:
            messages.error(request, 'Please correct the errors below.')
    else:
        form = CategoryForm(instance=category)

    return render(request, 'category_form.html', {'form': form, 'category': category})




# product_list

def product_list(request):
    instances = Product.objects.all()

    context = {
            "instances": instances,
            
    }
    return render(request, 'manager/product_list.html', context=context)




def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('manager:product_list')  # Adjust the redirect to your desired URL
    else:
        form = ProductForm()
    return render(request, 'manager/product_form.html', {'form': form})

def edit_product(request, id):
    product = get_object_or_404(Product, id=id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('manager:product_list')  # Adjust the redirect
    else:
        form = ProductForm(instance=product)
    return render(request, 'manager/product_form.html', {'form': form})

def delete_product(request, id):
    product = get_object_or_404(Product, id=id)
    
    product.delete()
    
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



# product_list

def orders_list(request):
    instances = Order.objects.all()
    instances_items = OrderItem.objects.all()

    context = {
            "instances": instances,
            "instances_items": instances_items,
            
    }
    return render(request, 'manager/orders_list.html', context=context)




def order_track(request, id):
    instance = Order.objects.get(id=id)
    if instance.status == 'Pending':
        instance.status = 'Preparing'
        instance.save()

    elif instance.status == 'Preparing':
        instance.status = 'Ready for Pickup/Delivery'
        instance.save()
        
    elif instance.status == 'Ready for Pickup/Delivery':
        instance.status = 'Dispatched'
        instance.save()
        
    elif instance.status == 'Dispatched':
        instance.status = 'Delivered'
        instance.save()
    
    
    # return render(request, 'manager/forms/order_track.html', context=context)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def cancel_order(request, id):
    instance = Order.objects.get(id=id)

    if instance.status != 'Cancelled':
        instance.status = 'Cancelled'
        instance.save()
        messages.success(request, "Order has been cancelled.")
    else:
        messages.warning(request, "This order is already cancelled.")

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

product/views.py
from django.shortcuts import render

# Create your views here.

templates/manager/category_form.html
{% extends 'base/manager-base.html' %} 
{% load static %} 
{% block container %}

    <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        {% include 'include/manager-nav.html' %}
        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                               
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Restorant Category Input File</h4>
                                <div class="basic-form">
                                   
                                    <form method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <div class="mb-3">
                                            {{ form.name.label_tag }}
                                            {{ form.name }}
                                            {% for error in form.name.errors %}
                                                <div class="text-danger">{{ error }}</div>
                                            {% endfor %}
                                        </div>
                                        <div class="mb-3">
                                            {{ form.description.label_tag }}
                                            {{ form.description }}
                                            {% for error in form.description.errors %}
                                                <div class="text-danger">{{ error }}</div>
                                            {% endfor %}
                                        </div>
                                        <div class="mb-3">
                                            {{ form.image.label_tag }}
                                            {{ form.image }}
                                            {% for error in form.image.errors %}
                                                <div class="text-danger">{{ error }}</div>
                                            {% endfor %}
                                        </div>
                                        <div class="mb-3">
                                            {{ form.slug.label_tag }}
                                            {{ form.slug }}
                                            {% for error in form.slug.errors %}
                                                <div class="text-danger">{{ error }}</div>
                                            {% endfor %}
                                        </div>
                                        <button type="submit" class="btn btn-primary">Save Category</button>
                                    </form>
                                    
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    
                    
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        {% endblock %}

templates/manager/category_list.html
{% extends 'base/manager-base.html' %} 
{% load static %} 
{% block container %}

<!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        
    {% include 'include/manager-nav.html' %}

        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Food Category Table</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Name</th>
                                                <th>Image</th>
                                                <th>Edit</th>
                                                <th>Delet</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                            <tr>
                                                <td>{{ instance.id }}</td>
                                                <td>{{ instance.name }}</td>
                                                <td>{{ instance.description }}</td>
                                                <td>{{ instance.slug }}</td>
                                                <td>
                                                    {% if instance.image %}
                                                        <img src="{{ instance.image.url }}" alt="{{ instance.name }}" style="width: 100px; height: 100px;">
                                                    {% else %}
                                                        <span>No Image Available</span>
                                                    {% endif %}
                                                </td>
                                                <td><a href="{% url 'manager:edit_category' id=instance.id %}"><button type="button" class="btn mb-1 btn-primary">Edit</button></a></td>
                                                <td><a href="{% url 'manager:delete_category' id=instance.id %}"><button type="button" class="btn mb-1 btn-danger">Delete</button></a></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    {% endblock %}

templates/manager/product_list.html
{% extends 'base/manager-base.html' %} 
{% load static %} 
{% block container %}

<!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        
    {% include 'include/manager-nav.html' %}

        <!--**********************************
            Content body start
        ***********************************-->
        <div class="content-body">

            <div class="row page-titles mx-0">
                <div class="col p-md-0">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="javascript:void(0)">Dashboard</a></li>
                        <li class="breadcrumb-item active"><a href="javascript:void(0)">Home</a></li>
                    </ol>
                </div>
            </div>
            <!-- row -->

            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">Food Category Table</h4>
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered zero-configuration">
                                        <thead>
                                            <tr>
                                                <th>ID</th>
                                                <th>Name</th>
                                                <th>Description</th>
                                                <th>Price</th>
                                                <th>Category</th>
                                                <th>stock</th>
                                                <th>weight</th>
                                                <th>is_active</th>
                                                <th>created_at</th>
                                                <th>Image</th>
                                                <th>Image 2</th>
                                                <th>Image 3</th>
                                                <th>Image 4</th>
                                                <th>Edit</th>
                                                <th>Delet</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for instance in instances %}
                                            <tr>
                                                <td>{{ instance.id }}</td>
                                                <td>{{ instance.name }}</td>
                                                <td>{{ instance.description }}</td>
                                                <td>{{ instance.price }}</td>
                                                <td>{{ instance.category }}</td>
                                                <td>{{ instance.stock }}</td>
                                                <td>{{ instance.weight }}</td>
                                                <td>{{ instance.is_active }}</td>
                                                <td>{{ instance.created_at }}</td>
                                                <td>
                                                    {% if instance.image %}
                                                        <img src="{{ instance.image.url }}" alt="{{ instance.name }}" style="width: 100px; height: 100px;">
                                                    {% else %}
                                                        <span>No Image Available</span>
                                                    {% endif %}
                                                </td>
                                                <td>
                                                    {% if instance.image_2 %}
                                                        <img src="{{ instance.image_2.url }}" alt="{{ instance.name }}" style="width: 100px; height: 100px;">
                                                    {% else %}
                                                        <span>No Image Available</span>
                                                    {% endif %}
                                                </td>
                                                <td>
                                                    {% if instance.image_3 %}
                                                        <img src="{{ instance.image_3.url }}" alt="{{ instance.name }}" style="width: 100px; height: 100px;">
                                                    {% else %}
                                                        <span>No Image Available</span>
                                                    {% endif %}
                                                </td>
                                                <td>
                                                    {% if instance.image_4 %}
                                                        <img src="{{ instance.image_4.url }}" alt="{{ instance.name }}" style="width: 100px; height: 100px;">
                                                    {% else %}
                                                        <span>No Image Available</span>
                                                    {% endif %}
                                                </td>
                                                <td><a href="{% url 'manager:edit_product' id=instance.id %}"><button type="button" class="btn mb-1 btn-primary">Edit</button></a></td>
                                                <td><a href="{% url 'manager:delete_product' id=instance.id %}"><button type="button" class="btn mb-1 btn-danger">Delete</button></a></td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th>ID</th>
                                                <th>Name</th>
                                                <th>Restorant</th>
                                                <th>Edit</th>
                                                <th>Delet</th>
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- #/ container -->
        </div>
        <!--**********************************
            Content body end
        ***********************************-->
        
        
        <!--**********************************
            Footer start
        ***********************************-->
        <div class="footer">
            <div class="copyright">
                <p>Copyright &copy; Designed & Developed by <a href="https://themeforest.net/user/quixlab">Quixlab</a> 2018</p>
            </div>
        </div>
        <!--**********************************
            Footer end
        ***********************************-->
    </div>
    <!--**********************************
        Main wrapper end
    ***********************************-->

    {% endblock %}

templates/manager/unauthorized_access.html
<!-- templates/unauthorized_access.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Unauthorized Access</title>
</head>
<body>
    <h1>Unauthorized Access</h1>
    <p>You can't access this page. You have been logged out.</p>
</body>
</html>